package ui

import "fyne.io/fyne/v2"

// fonts returns the bundled font resources per weight role.
// Oswald = headings/labels (Bold slot), Rajdhani = body (Regular slot);
// generated by `fyne bundle` from fonts_src/ (committed, OFL).
func fonts() map[string]fyne.Resource {
	return map[string]fyne.Resource{
		"oswald":   resourceOswaldTtf,
		"rajdhani": resourceRajdhaniTtf,
	}
}
