// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConfigPaths():Promise<Record<string, any>>;

export function Configured():Promise<boolean>;

export function Detect():Promise<Record<string, any>>;

export function DownloadGibbed():Promise<Record<string, any>>;

export function GameStatus():Promise<Record<string, any>>;

export function OpenPath(arg1:string):Promise<void>;

export function SelectFolder(arg1:string):Promise<string>;

export function SetupSave(arg1:Record<string, any>):Promise<Record<string, any>>;
