// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConfigPaths() {
  return window['go']['bridge']['App']['ConfigPaths']();
}

export function Configured() {
  return window['go']['bridge']['App']['Configured']();
}

export function Detect() {
  return window['go']['bridge']['App']['Detect']();
}

export function DownloadGibbed() {
  return window['go']['bridge']['App']['DownloadGibbed']();
}

export function GameStatus() {
  return window['go']['bridge']['App']['GameStatus']();
}

export function OpenPath(arg1) {
  return window['go']['bridge']['App']['OpenPath'](arg1);
}

export function SelectFolder(arg1) {
  return window['go']['bridge']['App']['SelectFolder'](arg1);
}

export function SetupSave(arg1) {
  return window['go']['bridge']['App']['SetupSave'](arg1);
}
