// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AllBalances():Promise<any>;

export function AllPartsBatch(arg1:string,arg2:string):Promise<Record<string, any>>;

export function AllPartsForSlot(arg1:string,arg2:string):Promise<any>;

export function Balances(arg1:string):Promise<any>;

export function Customizations(arg1:string):Promise<any>;

export function ItemBalances(arg1:string):Promise<any>;

export function ItemCategories():Promise<any>;

export function ItemParts(arg1:string):Promise<any>;

export function Manufacturers():Promise<any>;

export function Parts(arg1:string):Promise<any>;

export function WeaponTypes():Promise<any>;
