// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AllBalances() {
  return window['go']['bridge']['Assets']['AllBalances']();
}

export function AllPartsBatch(arg1, arg2) {
  return window['go']['bridge']['Assets']['AllPartsBatch'](arg1, arg2);
}

export function AllPartsForSlot(arg1, arg2) {
  return window['go']['bridge']['Assets']['AllPartsForSlot'](arg1, arg2);
}

export function Balances(arg1) {
  return window['go']['bridge']['Assets']['Balances'](arg1);
}

export function Customizations(arg1) {
  return window['go']['bridge']['Assets']['Customizations'](arg1);
}

export function ItemBalances(arg1) {
  return window['go']['bridge']['Assets']['ItemBalances'](arg1);
}

export function ItemCategories() {
  return window['go']['bridge']['Assets']['ItemCategories']();
}

export function ItemParts(arg1) {
  return window['go']['bridge']['Assets']['ItemParts'](arg1);
}

export function Manufacturers() {
  return window['go']['bridge']['Assets']['Manufacturers']();
}

export function Parts(arg1) {
  return window['go']['bridge']['Assets']['Parts'](arg1);
}

export function WeaponTypes() {
  return window['go']['bridge']['Assets']['WeaponTypes']();
}
