// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddAllStory(arg1:string,arg2:number,arg3:Record<string, any>):Promise<Record<string, any>>;

export function AddMission(arg1:string,arg2:number,arg3:Record<string, any>):Promise<Record<string, any>>;

export function AllStations():Promise<Array<Record<string, any>>>;

export function CompleteAllChallenges(arg1:string):Promise<Record<string, any>>;

export function CompleteAllMissions(arg1:string,arg2:number):Promise<Record<string, any>>;

export function FillAmmo(arg1:string):Promise<Record<string, any>>;

export function GetChallenges(arg1:string):Promise<any>;

export function MissionDB():Promise<any>;

export function Playthrough(arg1:string,arg2:Record<string, any>):Promise<Record<string, any>>;

export function RemoveMission(arg1:string,arg2:number,arg3:Record<string, any>):Promise<Record<string, any>>;

export function ResetAllChallenges(arg1:string):Promise<Record<string, any>>;

export function SetActiveMission(arg1:string,arg2:number,arg3:Record<string, any>):Promise<Record<string, any>>;

export function SetAmmo(arg1:string,arg2:Record<string, any>):Promise<Record<string, any>>;

export function SetChallenge(arg1:string,arg2:Record<string, any>):Promise<Record<string, any>>;

export function SetMissionStatus(arg1:string,arg2:number,arg3:string,arg4:Record<string, any>):Promise<Record<string, any>>;

export function SetSkills(arg1:string,arg2:Record<string, any>):Promise<Record<string, any>>;

export function SpawnTestWeapons(arg1:string):Promise<any>;

export function UnlockAchievements(arg1:string):Promise<Record<string, any>>;

export function UnlockAllFastTravel(arg1:string):Promise<Record<string, any>>;

export function UpdateCharacter(arg1:string,arg2:Record<string, any>):Promise<any>;

export function UpdateFastTravel(arg1:string,arg2:Record<string, any>):Promise<Record<string, any>>;
