// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddAllStory(arg1, arg2, arg3) {
  return window['go']['bridge']['Editor']['AddAllStory'](arg1, arg2, arg3);
}

export function AddMission(arg1, arg2, arg3) {
  return window['go']['bridge']['Editor']['AddMission'](arg1, arg2, arg3);
}

export function AllStations() {
  return window['go']['bridge']['Editor']['AllStations']();
}

export function CompleteAllChallenges(arg1) {
  return window['go']['bridge']['Editor']['CompleteAllChallenges'](arg1);
}

export function CompleteAllMissions(arg1, arg2) {
  return window['go']['bridge']['Editor']['CompleteAllMissions'](arg1, arg2);
}

export function FillAmmo(arg1) {
  return window['go']['bridge']['Editor']['FillAmmo'](arg1);
}

export function GetChallenges(arg1) {
  return window['go']['bridge']['Editor']['GetChallenges'](arg1);
}

export function MissionDB() {
  return window['go']['bridge']['Editor']['MissionDB']();
}

export function Playthrough(arg1, arg2) {
  return window['go']['bridge']['Editor']['Playthrough'](arg1, arg2);
}

export function RemoveMission(arg1, arg2, arg3) {
  return window['go']['bridge']['Editor']['RemoveMission'](arg1, arg2, arg3);
}

export function ResetAllChallenges(arg1) {
  return window['go']['bridge']['Editor']['ResetAllChallenges'](arg1);
}

export function SetActiveMission(arg1, arg2, arg3) {
  return window['go']['bridge']['Editor']['SetActiveMission'](arg1, arg2, arg3);
}

export function SetAmmo(arg1, arg2) {
  return window['go']['bridge']['Editor']['SetAmmo'](arg1, arg2);
}

export function SetChallenge(arg1, arg2) {
  return window['go']['bridge']['Editor']['SetChallenge'](arg1, arg2);
}

export function SetMissionStatus(arg1, arg2, arg3, arg4) {
  return window['go']['bridge']['Editor']['SetMissionStatus'](arg1, arg2, arg3, arg4);
}

export function SetSkills(arg1, arg2) {
  return window['go']['bridge']['Editor']['SetSkills'](arg1, arg2);
}

export function SpawnTestWeapons(arg1) {
  return window['go']['bridge']['Editor']['SpawnTestWeapons'](arg1);
}

export function UnlockAchievements(arg1) {
  return window['go']['bridge']['Editor']['UnlockAchievements'](arg1);
}

export function UnlockAllFastTravel(arg1) {
  return window['go']['bridge']['Editor']['UnlockAllFastTravel'](arg1);
}

export function UpdateCharacter(arg1, arg2) {
  return window['go']['bridge']['Editor']['UpdateCharacter'](arg1, arg2);
}

export function UpdateFastTravel(arg1, arg2) {
  return window['go']['bridge']['Editor']['UpdateFastTravel'](arg1, arg2);
}
