// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddItem(arg1, arg2) {
  return window['go']['bridge']['Items']['AddItem'](arg1, arg2);
}

export function AddWeapon(arg1, arg2) {
  return window['go']['bridge']['Items']['AddWeapon'](arg1, arg2);
}

export function BulkLevel(arg1, arg2, arg3) {
  return window['go']['bridge']['Items']['BulkLevel'](arg1, arg2, arg3);
}

export function DeleteItem(arg1, arg2, arg3) {
  return window['go']['bridge']['Items']['DeleteItem'](arg1, arg2, arg3);
}

export function DeleteLoadout(arg1) {
  return window['go']['bridge']['Items']['DeleteLoadout'](arg1);
}

export function DuplicateItem(arg1, arg2, arg3) {
  return window['go']['bridge']['Items']['DuplicateItem'](arg1, arg2, arg3);
}

export function EditItem(arg1, arg2, arg3, arg4) {
  return window['go']['bridge']['Items']['EditItem'](arg1, arg2, arg3, arg4);
}

export function ExportAll(arg1) {
  return window['go']['bridge']['Items']['ExportAll'](arg1);
}

export function ExportCode(arg1, arg2, arg3) {
  return window['go']['bridge']['Items']['ExportCode'](arg1, arg2, arg3);
}

export function ImportCodes(arg1, arg2) {
  return window['go']['bridge']['Items']['ImportCodes'](arg1, arg2);
}

export function ListLoadouts() {
  return window['go']['bridge']['Items']['ListLoadouts']();
}

export function PreviewCodes(arg1) {
  return window['go']['bridge']['Items']['PreviewCodes'](arg1);
}

export function ReorderItem(arg1, arg2, arg3) {
  return window['go']['bridge']['Items']['ReorderItem'](arg1, arg2, arg3);
}

export function RestoreLoadout(arg1, arg2, arg3) {
  return window['go']['bridge']['Items']['RestoreLoadout'](arg1, arg2, arg3);
}

export function SaveLoadout(arg1) {
  return window['go']['bridge']['Items']['SaveLoadout'](arg1);
}

export function SetItemLevel(arg1, arg2, arg3, arg4) {
  return window['go']['bridge']['Items']['SetItemLevel'](arg1, arg2, arg3, arg4);
}

export function TransferItem(arg1, arg2, arg3, arg4) {
  return window['go']['bridge']['Items']['TransferItem'](arg1, arg2, arg3, arg4);
}
