// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddItem(arg1:string,arg2:Record<string, any>):Promise<Record<string, any>>;

export function AddWeapon(arg1:string,arg2:Record<string, any>):Promise<Record<string, any>>;

export function BulkLevel(arg1:string,arg2:number,arg3:Record<string, any>):Promise<Record<string, any>>;

export function DeleteItem(arg1:string,arg2:number,arg3:number):Promise<Record<string, any>>;

export function DeleteLoadout(arg1:string):Promise<Record<string, any>>;

export function DuplicateItem(arg1:string,arg2:number,arg3:number):Promise<Record<string, any>>;

export function EditItem(arg1:string,arg2:number,arg3:number,arg4:Record<string, any>):Promise<Record<string, any>>;

export function ExportAll(arg1:string):Promise<any>;

export function ExportCode(arg1:string,arg2:number,arg3:number):Promise<Record<string, any>>;

export function ImportCodes(arg1:string,arg2:Record<string, any>):Promise<Record<string, any>>;

export function ListLoadouts():Promise<any>;

export function PreviewCodes(arg1:Record<string, any>):Promise<any>;

export function ReorderItem(arg1:string,arg2:number,arg3:Record<string, any>):Promise<Record<string, any>>;

export function RestoreLoadout(arg1:string,arg2:string,arg3:Record<string, any>):Promise<Record<string, any>>;

export function SaveLoadout(arg1:Record<string, any>):Promise<any>;

export function SetItemLevel(arg1:string,arg2:number,arg3:number,arg4:Record<string, any>):Promise<Record<string, any>>;

export function TransferItem(arg1:string,arg2:number,arg3:number,arg4:Record<string, any>):Promise<Record<string, any>>;
