// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteSave(arg1) {
  return window['go']['bridge']['Saves']['DeleteSave'](arg1);
}

export function DuplicateSave(arg1) {
  return window['go']['bridge']['Saves']['DuplicateSave'](arg1);
}

export function ListBackups(arg1) {
  return window['go']['bridge']['Saves']['ListBackups'](arg1);
}

export function ListSaves() {
  return window['go']['bridge']['Saves']['ListSaves']();
}

export function LoadSave(arg1) {
  return window['go']['bridge']['Saves']['LoadSave'](arg1);
}

export function RestoreBackup(arg1, arg2) {
  return window['go']['bridge']['Saves']['RestoreBackup'](arg1, arg2);
}

export function SavePreviews() {
  return window['go']['bridge']['Saves']['SavePreviews']();
}
