// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteSave(arg1:string):Promise<Record<string, any>>;

export function DuplicateSave(arg1:string):Promise<Record<string, any>>;

export function ListBackups(arg1:string):Promise<Record<string, any>>;

export function ListSaves():Promise<Array<Record<string, any>>>;

export function LoadSave(arg1:string):Promise<Record<string, any>>;

export function RestoreBackup(arg1:string,arg2:Record<string, any>):Promise<Record<string, any>>;

export function SavePreviews():Promise<Record<string, any>>;
