// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Achievements() {
  return window['go']['bridge']['Steam']['Achievements']();
}

export function Clear() {
  return window['go']['bridge']['Steam']['Clear']();
}

export function Init() {
  return window['go']['bridge']['Steam']['Init']();
}

export function Status() {
  return window['go']['bridge']['Steam']['Status']();
}

export function Unlock() {
  return window['go']['bridge']['Steam']['Unlock']();
}

export function UnlockAll() {
  return window['go']['bridge']['Steam']['UnlockAll']();
}
