// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Achievements():Promise<Array<Record<string, any>>>;

export function Clear():Promise<void>;

export function Init():Promise<Record<string, any>>;

export function Status():Promise<Record<string, any>>;

export function Unlock():Promise<void>;

export function UnlockAll():Promise<void>;
